export const RESET_FORM = "COMPOSE_EMAIL/RESET_FORM";
export const SET_FORM = "COMPOSE_EMAIL/SET_FORM";
export const SET_FORM_FIELD = "COMPOSE_EMAIL/SET_FORM_FIELD";
export const SHOW = "COMPOSE_EMAIL/SHOW";
